export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const UPDATE_FIELD = 'UPDATE_FIELD';
export const RESET_FORM = 'RESET_FORM';

export const AUTH_CHECK_FALSE = 'AUTH_CHECK_FALSE';
export const AUTH_CHECK_TRUE = 'AUTH_CHECK_TRUE';

export const FETCH_USERS = 'FETCH_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';