export const ACTIVE_MENU_ITEM = 'ACTIVE_MENU_ITEM';
export const SET_UPDATE_MODE = 'SET_UPDATE_MODE';
export const SET_EDITING_MODE = 'SET_EDITING_MODE';
export const MANAGE_PICTURE_MODE = 'MANAGE_PICTURE_MODE';

export const UPDATE_DESCRIPTION_SUCCESS = 'UPDATE_DESCRIPTION_SUCCESS';
export const UPDATE_DESCRIPTION_FAILURE = 'UPDATE_DESCRIPTION_FAILURE';
export const UPDATE_PWD = 'UPDATE_PWD';

export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';
export const FETCH_HASHTAGS_SUCCESS = 'FETCH_HASHTAGS_SUCCESS';
export const FETCH_HASHTAGS_FAILURE = 'FETCH_HASHTAGS_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const RESET_UPDATE = 'RESET_UPDATE';

export const ADD_HASHTAG = 'ADD_HASHTAG';
export const ADD_HASHTAG_FAILURE = 'ADD_HASHTAG_FAILURE';

export const DELETE_PICTURE_SUCCESS = 'DELETE_PICTURE_SUCCESS';
export const DELETE_PICTURE_FAILURE = 'DELETE_PICTURE_FAILURE';

export const DELETE_HASHTAG_SUCCESS = 'DELETE_HASHTAG_SUCCESS';
export const DELETE_HASHTAG_FAILURE = 'DELETE_HASHTAG_FAILURE';

export const UPLOAD_PICTURE_REQUEST = 'UPLOAD_PICTURE_REQUEST';
export const UPLOAD_PICTURE_SUCCESS = 'UPLOAD_PICTURE_SUCCESS';
export const UPLOAD_PICTURE_FAILURE = 'UPLOAD_PICTURE_FAILURE';

export const SUBMIT_PWD_SUCCESS = 'SUBMIT_PWD_SUCCESS';
export const SUBMIT_PWD_FAILURE = 'SUBMIT_PWD_FAILURE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const NEW_VISIT = 'NEW_VISIT';
export const REPORT_USER = 'REPORT_USER';
export const BLOCK_USER = 'BLOCK_USER';

export const COPY_USER = 'COPY_USER';
export const LOGOUT = 'LOGOUT';
