export const ACTIVE_MENU_ITEM = 'ACTIVE_MENU_ITEM';

export const SET_UPDATE_MODE = 'SET_UPDATE_MODE';
export const UPDATE_USER_FIELD = 'UPDATE_USER_FIELD';
export const FETCH_HASHTAGS_SUCCESS = 'FETCH_HASHTAGS_SUCCESS';
export const FETCH_HASHTAGS_FAILURE = 'FETCH_HASHTAGS_FAILURE';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const RESET_UPDATE = 'RESET_UPDATE';

export const COPY_USER = 'COPY_USER';
export const LOGOUT = 'LOGOUT';
